"""primera migracion

Revision ID: a27c2313e139
Revises: 
Create Date: 2025-11-22 16:57:32.590633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a27c2313e139'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultorios',
    sa.Column('id_consultorio', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('numero_consultorio', sa.String(), nullable=False),
    sa.Column('piso', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_consultorio')
    )
    op.create_table('especialidades',
    sa.Column('id_especialidad', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_especialidad'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('estados_turnos',
    sa.Column('id_estado_turno', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_estado_turno'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('medicos',
    sa.Column('id_medico', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_usuario', sa.Uuid(), nullable=True),
    sa.Column('matricula', sa.String(), nullable=False),
    sa.Column('dni', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_medico'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('id_usuario'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('pacientes',
    sa.Column('id_paciente', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_usuario', sa.Uuid(), nullable=True),
    sa.Column('dni', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_paciente'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_table('roles_x_usuarios',
    sa.Column('id_roles_x_usuario', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_usuario', sa.Uuid(), nullable=False),
    sa.Column('id_rol', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_roles_x_usuario')
    )
    op.create_table('agendas_medicos',
    sa.Column('id_agenda', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_medico', sa.Uuid(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('duracion_turno', sa.Integer(), nullable=False),
    sa.Column('jornada', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_medico'], ['medicos.id_medico'], ),
    sa.PrimaryKeyConstraint('id_agenda'),
    sa.UniqueConstraint('id_medico', 'dia_semana', 'hora_inicio')
    )
    op.create_table('asignacion_consultorios',
    sa.Column('id_asignacion', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_medico', sa.Uuid(), nullable=False),
    sa.Column('id_consultorio', sa.Uuid(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('jornada', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_consultorio'], ['consultorios.id_consultorio'], ),
    sa.ForeignKeyConstraint(['id_medico'], ['medicos.id_medico'], ),
    sa.PrimaryKeyConstraint('id_asignacion'),
    sa.UniqueConstraint('id_consultorio', 'jornada', 'fecha_inicio', 'fecha_fin')
    )
    op.create_table(
    "medico_especialidad",
    sa.Column("id_medico", sa.Uuid(), sa.ForeignKey("medicos.id_medico"), primary_key=True, nullable=False),
    sa.Column("id_especialidad", sa.Uuid(), sa.ForeignKey("especialidades.id_especialidad"), primary_key=True, nullable=False),
)
    op.create_table('turnos',
    sa.Column('id_turno', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_paciente', sa.Uuid(), nullable=False),
    sa.Column('id_medico', sa.Uuid(), nullable=False),
    sa.Column('id_consultorio', sa.Uuid(), nullable=False),
    sa.Column('id_estado_turno', sa.Uuid(), nullable=False),
    sa.Column('fecha_hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_hora_fin', sa.DateTime(), nullable=False),
    sa.Column('motivo_consulta', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_consultorio'], ['consultorios.id_consultorio'], ),
    sa.ForeignKeyConstraint(['id_estado_turno'], ['estados_turnos.id_estado_turno'], ),
    sa.ForeignKeyConstraint(['id_medico'], ['medicos.id_medico'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.PrimaryKeyConstraint('id_turno'),
    sa.UniqueConstraint('id_consultorio', 'fecha_hora_inicio'),
    sa.UniqueConstraint('id_medico', 'fecha_hora_inicio')
    )
    op.create_table('historial_eventos',
    sa.Column('id_evento', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_turno', sa.Uuid(), nullable=False),
    sa.Column('fecha_evento', sa.DateTime(), nullable=False),
    sa.Column('tipo_evento', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('id_usuario', sa.Uuid(), nullable=True),
    sa.Column('motivo', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_turno'], ['turnos.id_turno'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_evento')
    )
    op.create_table('historias_clinicas',
    sa.Column('id_historia_clinica', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_paciente', sa.Uuid(), nullable=False),
    sa.Column('id_medico', sa.Uuid(), nullable=False),
    sa.Column('id_turno', sa.Uuid(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('tratamiento', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_medico'], ['medicos.id_medico'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.ForeignKeyConstraint(['id_turno'], ['turnos.id_turno'], ),
    sa.PrimaryKeyConstraint('id_historia_clinica')
    )
    op.create_table('recetas',
    sa.Column('id_receta', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_turno', sa.Uuid(), nullable=False),
    sa.Column('medicamentos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_turno'], ['turnos.id_turno'], ),
    sa.PrimaryKeyConstraint('id_receta')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recetas')
    op.drop_table('historias_clinicas')
    op.drop_table('historial_eventos')
    op.drop_table('turnos')
    op.drop_table('medico_especialidad')
    op.drop_table('asignacion_consultorios')
    op.drop_table('agendas_medicos')
    op.drop_table('roles_x_usuarios')
    op.drop_table('pacientes')
    op.drop_table('medicos')
    op.drop_table('usuarios')
    op.drop_table('roles')
    op.drop_table('estados_turnos')
    op.drop_table('especialidades')
    op.drop_table('consultorios')
    # ### end Alembic commands ###
