"""initial models

Revision ID: fc70ec428d0c
Revises: 
Create Date: 2025-11-15 19:02:08.842052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc70ec428d0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especialidades',
    sa.Column('id_especialidad', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_especialidad'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('medicos',
    sa.Column('id_medico', sa.Uuid(), nullable=False),
    sa.Column('matricula', sa.String(), nullable=False),
    sa.Column('dni', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_medico'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('pacientes',
    sa.Column('id_paciente', sa.Uuid(), nullable=False),
    sa.Column('dni', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_paciente'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email')
    )
    op.create_table('consultorios',
    sa.Column('id_consultorio', sa.Uuid(), nullable=False),
    sa.Column('numero_consultorio', sa.String(), nullable=False),
    sa.Column('piso', sa.String(), nullable=True),
    sa.Column('id_especialidad', sa.Uuid(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_especialidad'], ['especialidades.id_especialidad'], ),
    sa.PrimaryKeyConstraint('id_consultorio')
    )
    op.create_table('medico_especialidad',
    sa.Column('id_medico', sa.Uuid(), nullable=False),
    sa.Column('id_especialidad', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id_especialidad'], ['especialidades.id_especialidad'], ),
    sa.ForeignKeyConstraint(['id_medico'], ['medicos.id_medico'], ),
    sa.PrimaryKeyConstraint('id_medico', 'id_especialidad')
    )
    op.create_table('disponibilidad_consultorios',
    sa.Column('id_disponibilidad', sa.Uuid(), nullable=False),
    sa.Column('id_medico', sa.Uuid(), nullable=False),
    sa.Column('id_consultorio', sa.Uuid(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['id_consultorio'], ['consultorios.id_consultorio'], ),
    sa.ForeignKeyConstraint(['id_medico'], ['medicos.id_medico'], ),
    sa.PrimaryKeyConstraint('id_disponibilidad'),
    sa.UniqueConstraint('id_consultorio', 'dia_semana', 'hora_inicio')
    )
    op.create_table('turnos',
    sa.Column('id_turno', sa.Uuid(), nullable=False),
    sa.Column('id_paciente', sa.Uuid(), nullable=False),
    sa.Column('id_medico', sa.Uuid(), nullable=False),
    sa.Column('id_consultorio', sa.Uuid(), nullable=False),
    sa.Column('fecha_hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_hora_fin', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('motivo_consulta', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_consultorio'], ['consultorios.id_consultorio'], ),
    sa.ForeignKeyConstraint(['id_medico'], ['medicos.id_medico'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.PrimaryKeyConstraint('id_turno'),
    sa.UniqueConstraint('id_consultorio', 'fecha_hora_inicio'),
    sa.UniqueConstraint('id_medico', 'fecha_hora_inicio')
    )
    op.create_table('historias_clinicas',
    sa.Column('id_entrada_historia', sa.Uuid(), nullable=False),
    sa.Column('id_paciente', sa.Uuid(), nullable=False),
    sa.Column('id_medico', sa.Uuid(), nullable=False),
    sa.Column('id_turno', sa.Uuid(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('tratamiento', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_medico'], ['medicos.id_medico'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.ForeignKeyConstraint(['id_turno'], ['turnos.id_turno'], ),
    sa.PrimaryKeyConstraint('id_entrada_historia')
    )
    op.create_table('recetas',
    sa.Column('id_receta', sa.Uuid(), nullable=False),
    sa.Column('id_turno', sa.Uuid(), nullable=False),
    sa.Column('fecha_emision', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('medicamentos', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id_turno'], ['turnos.id_turno'], ),
    sa.PrimaryKeyConstraint('id_receta')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recetas')
    op.drop_table('historias_clinicas')
    op.drop_table('turnos')
    op.drop_table('disponibilidad_consultorios')
    op.drop_table('medico_especialidad')
    op.drop_table('consultorios')
    op.drop_table('pacientes')
    op.drop_table('medicos')
    op.drop_table('especialidades')
    # ### end Alembic commands ###
